"""Equal Repeats, using the historical DeepMind task's inclusive sampling bounds.

Semantic reference (Apache-2.0): google-deepmind/neural_networks_chomsky_hierarchy,
46bcae06945726f34e8e4560ab698fa2f2d2c889/tasks/ndcf/equal_repeats.py.
Empty runs at even-length endpoints and class-0 priority for equal-all are intentional.
"""
import hashlib
import json

import torch
from torch.nn import functional as F

SYMBOLS = ('0', '1')
SEMANTICS_VERSION = 'deepmind-equal-repeats-v1'
REFERENCE_REVISION = '46bcae06945726f34e8e4560ab698fa2f2d2c889'
REFERENCE_URL = ('https://github.com/google-deepmind/neural_networks_chomsky_hierarchy/blob/'
                 f'{REFERENCE_REVISION}/tasks/ndcf/equal_repeats.py')
REFERENCE_SHA256 = 'bbbf7b99d1c4ac13f0d979abd2ee3b6f7f73311c7666ad234b9c8260ebf504fd'


def validate_length(length):
    if type(length) is not int or length < 2:
        raise ValueError('Equal Repeats length must be an integer >= 2')


def classify_sequence(sequence):
    """Diagnostic oracle; counts are never supplied to the model."""
    bits = list(sequence)
    if not bits or any(str(bit) not in ('0', '1') for bit in bits):
        raise ValueError('Expected a nonempty binary sequence')
    bits = [int(bit) for bit in bits]
    validate_length(len(bits))
    if not any(bits):
        # The original class-2 endpoint has a zero-length middle run.
        if len(bits) % 2:
            raise ValueError('An all-zero odd-length sequence is not generated by this task')
        return 2
    left = bits.index(1)
    stop = left
    while stop < len(bits) and bits[stop] == 1:
        stop += 1
    if any(bits[stop:]):
        raise ValueError('Expected one contiguous block of ones')
    middle, right = stop-left, len(bits)-stop
    if left == middle and left > 0:
        return 0
    if middle == right and right > 0:
        return 1
    if left == right and left > 0:
        return 2
    raise ValueError('No guaranteed equality relation')


def _sample_plan(batch_size, length, generator, *, permute=True):
    """Private generation plan, kept out of the public batch and model inputs."""
    validate_length(length)
    if type(batch_size) is not int or batch_size < 1:
        raise ValueError('batch_size must be a positive integer')
    if not isinstance(generator, torch.Generator) or generator.device.type != 'cpu':
        raise ValueError('Use a seeded CPU torch.Generator for reproducible data generation')
    count = batch_size//3
    remainder = batch_size-2*count
    a = torch.randint(1, length//2+1, (remainder,), generator=generator)
    paired = a[:count]
    starts = torch.cat((paired, length-2*paired, a))
    stops = torch.cat((2*paired, length-paired, length-a))
    labels = torch.cat((torch.zeros(count, dtype=torch.long), torch.ones(count, dtype=torch.long),
                        torch.full((remainder,), 2, dtype=torch.long)))
    if length % 3 == 0:
        labels[(starts == length//3) & (stops == 2*length//3)] = 0
    if permute:
        order = torch.randperm(batch_size, generator=generator)
        starts, stops, labels = starts[order], stops[order], labels[order]
    return starts, stops, labels


def _materialize_batch(plan, length):
    starts, stops, labels = plan
    positions = torch.arange(length)[None, :]
    bits = ((positions >= starts[:, None]) & (positions < stops[:, None])).long()
    return dict(inputs=F.one_hot(bits, num_classes=2).float(),
                attention_mask=torch.ones(len(labels), length, dtype=torch.bool),
                labels=labels.clone(), lengths=torch.full((len(labels),), length, dtype=torch.long))


def generate_equal_repeats_batch(batch_size, length, *, generator, permute=True):
    """Only binary one-hot input, mask, root label and total length leave the generator.

    The first two nominal groups are paired reversals. As in the reference, all
    three groups share sampled a values when their sizes match. PyTorch's PRNG
    replaces JAX's; cross-framework bit-for-bit random draws are not promised.
    Final class counts can change after the mandatory equal-all relabeling.
    """
    return _materialize_batch(_sample_plan(batch_size, length, generator, permute=permute), length)


def _evaluation_plan(count, length, seed):
    if type(seed) is not int or seed < 0:
        raise ValueError('Evaluation seed must be a nonnegative integer')
    # Stable across grid order, model family, and inference batch partitioning.
    digest = hashlib.sha256(f'{SEMANTICS_VERSION}:{seed}:{length}'.encode()).digest()
    generator = torch.Generator().manual_seed(int.from_bytes(digest[:8], 'little') % (2**63))
    plan = _sample_plan(count, length, generator)
    fingerprint = hashlib.sha256(json.dumps([x.tolist() for x in plan], separators=(',', ':')).encode()).hexdigest()
    return plan, fingerprint


def iter_evaluation_batches(count, length, *, seed, batch_size):
    if type(batch_size) is not int or batch_size < 1:
        raise ValueError('Evaluation batch_size must be positive')
    plan, _ = _evaluation_plan(count, length, seed)
    for start in range(0, count, batch_size):
        yield _materialize_batch(tuple(x[start:start+batch_size] for x in plan), length)
